SELECT c.ITEM_ID, c.ITEM_NAME, c.RARITY
FROM ITEM_TREE t
JOIN ITEM_INFO parent ON t.PARENT_ITEM_ID = parent.ITEM_ID
JOIN ITEM_INFO c      ON c.ITEM_ID = t.ITEM_ID
WHERE parent.RARITY = 'RARE'
ORDER BY c.ITEM_ID DESC;
