-- 코드를 입력하세요
SELECT
    C.INGREDIENT_TYPE,
    SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF AS F
INNER JOIN ICECREAM_INFO AS C
ON F.FLAVOR = C.FLAVOR
GROUP BY C.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC;


-- 